### PR TITLE
Update to MC 1.11.2

### PR DESCRIPTION
**Pull request by AfterRebelion**
This update is a direct update of the 1.9 codebase.
It would be better to redo the mod as a capability, but this is only to make it work for the time being.

### CODE REVIEW

**Comment by Claycorp** [comment]
Has this been tested at all yet?

**Comment by AfterRebelion** [comment]
I tested it, and seems to work:
image
Things confirmed to be working are:
- global and per dimension banning
- unbanning
- banning items with different damage values
- /list command
- pack and unpack work the same way as on 1.10

**Comment by dries007** [comment]
I don't want to be annoying, but would you please change the modname back to `ItemBlacklist` and only change the ID to `itemblacklist`. Also update it so the updateURL uses the name, not the ID. (So the archiveBaseName is still the same as it was.)

Thank you very much for updating this.

**Comment by dries007** [comment]
Thank you very much again.

**Pull request merged**
